import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { chakudyaClient } from "../clients/chakudyaClient.js";
import { ok, safeTool } from "../utils/toolResult.js";

interface RagAskResponseData {
  answer: string;
  intent: string;
  barcode_detected: string | null;
  sources: Array<{ id: number; source: string; title: string }>;
}

export function registerRagTools(server: McpServer) {
  // ── rag_retrieve ─────────────────────────────────────────────────────────
  server.registerTool(
    "rag_retrieve",
    {
      title: "RAG Retrieve (Raw Semantic Chunks)",
      description:
        "Semantic search over the Chakudya RAG knowledge base (includes ingested nutrition textbook " +
        "content) and return the raw matching chunks — no LLM-generated answer, just the ranked source " +
        "passages. Use this when you want to read/cite the underlying material yourself rather than get " +
        "a synthesized answer.",
      inputSchema: {
        query: z.string().min(1),
        context: z.enum(["both", "oasis", "thanzi"]).optional().default("both"),
        top_k: z.number().int().positive().max(20).optional().default(5),
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    safeTool("rag_retrieve", async ({ query, context, top_k }) => {
      const res = await chakudyaClient.post("/rag/retrieve", { query, context, top_k });
      return ok(res.data ?? res);
    })
  );

  // ── search_guidelines ────────────────────────────────────────────────────
  server.registerTool(
    "search_guidelines",
    {
      title: "Search Clinical Nutrition Guidelines",
      description:
        "Ask a clinical nutrition guideline question and get a grounded answer with numbered citations, " +
        "generated by the Chakudya RAG orchestrator (semantic search + rerank + LLM answer). Best for " +
        "questions like 'what is the recommended protein intake for a stage 3 CKD patient' where you want " +
        "a synthesized, cited answer rather than raw passages.",
      inputSchema: {
        query: z.string().min(1),
        top_k: z.number().int().positive().max(20).optional().default(6),
        session_id: z
          .string()
          .optional()
          .describe("Optional Oasis session id to personalize with that session's recalled memory"),
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    safeTool("search_guidelines", async ({ query, top_k, session_id }) => {
      const res = await chakudyaClient.post<RagAskResponseData>("/rag/ask", {
        query,
        context: "clinical",
        top_k,
        session_id,
      });
      return ok(res.data);
    })
  );

  // ── retrieve_evidence ────────────────────────────────────────────────────
  server.registerTool(
    "retrieve_evidence",
    {
      title: "Retrieve Supporting Evidence",
      description:
        "Retrieve a broader evidence base for a nutrition topic — runs the same grounded RAG orchestrator " +
        "as search_guidelines but with context='both' (clinical + general sources) and a higher default " +
        "top_k, for when you need wider supporting evidence rather than a narrow clinical-guideline answer.",
      inputSchema: {
        query: z.string().min(1),
        top_k: z.number().int().positive().max(20).optional().default(8),
      },
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: true,
      },
    },
    safeTool("retrieve_evidence", async ({ query, top_k }) => {
      const res = await chakudyaClient.post<RagAskResponseData>("/rag/ask", {
        query,
        context: "both",
        top_k,
      });
      return ok(res.data);
    })
  );
}
